services:
  - type: web
    name: ai-telegram-bot
    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: python main.py

    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: OPENROUTER_API_KEY
        sync: false

      - key: ADMIN_ID
        sync: false

      - key: ADMIN_PASSWORD
        sync: false
